stages:
  - build
  - lint
  - format
  - migrations
  - tests
  - deploy

default:
  tags:
    - deploy

build-job:
  stage: build
  before_script:
    - echo "$ENV" > .env
    - echo "$TEST_ENV" > .env-test
  script:
    - docker build -t booking_image .

Lint-job:
  stage: lint
  script:
    - docker run --rm booking_image ruff check

Format-job:
  stage: format
  script:
    - docker run --rm booking_image ruff format --check

Migrations-job:
  stage: migrations
  script:
    - docker run --rm --network booking_project_myNetwork booking_image alembic upgrade head

Tests-job:
  stage: tests
  script:
    - docker run --rm --network booking_project_myNetwork booking_image pytest -s -v

deploy-job:
  stage: deploy
  script:
    - cd /root/booking_project
    - git fetch origin main
    - git reset --hard origin/main
    - echo "$ENV" > .env
    - docker compose up -d --build
    - docker exec booking_nginx_container nginx -s reload
  only:
    - main

