services:
  booking_db:
    image: postgres:16
    container_name: booking_db_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-1234}
      POSTGRES_DB: ${DB_NAME:-booking}
    volumes:
      - booking_db_data:/var/lib/postgresql/data
    networks:
      - myNetwork

  booking_cache:
    image: redis:7.4
    container_name: booking_cache_container
    networks:
      - myNetwork

  booking_back_service:
    container_name: "booking_back_container"
    build:
      context: .
    networks:
      - myNetwork
    env_file:
      - .env
    depends_on:
      - booking_db
      - booking_cache

  booking_nginx:
    image: nginx:stable-alpine
    container_name: booking_nginx_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot_temp:/var/www/certbot:ro
    networks:
      - myNetwork
    depends_on:
      - booking_back_service

  booking_celery_worker_service:
    container_name: "booking_celery_worker_container"
    build:
      context: .
    networks:
      - myNetwork
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_application:celery_app worker -l INFO"

  booking_celery_beat_service:
    container_name: "booking_celery_beat_container"
    build:
      context: .
    networks:
      - myNetwork
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_application:celery_app beat -l INFO"

networks:
  myNetwork:
    driver: bridge

volumes:
  booking_db_data:
