events {}

http {
    # 1. Для выпуска/обновления серта
    server {
        listen 80;
        server_name dmitry-bat-booking-project.ru;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Редирект на https (вкл. после получения серта)
        location / {
            return 301 https://$host$request_uri;
        }
    }

    # 2. Блок для работы c сертом
    server {
        listen 443 ssl;
        server_name dmitry-bat-booking-project.ru;

        ssl_certificate /etc/letsencrypt/live/dmitry-bat-booking-project.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/dmitry-bat-booking-project.ru/privkey.pem;

        # для сертбота
        # include /etc/letsencrypt/options-ssl-nginx.conf;
        # ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

        location / {
            proxy_pass http://booking_back_service:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
